spring.application.name=CentralStation


bitcask.path=./bitcask_data
bitcask.max-file-size=10485760
bitcask.compaction-delay-ms=600000

server.port=8085
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=central-station-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.properties.specific.protobuf.value.type=com.diProject.broker.generated.StationMessage

