services:
  kafka:
    image: bitnamilegacy/kafka:latest

    ports:
      - "9092:9092"
      - "9094:9094"

    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - ALLOW_PLAINTEXT_LISTENER=yes

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0

    hostname: schema-registry

    container_name: schema-registry

    depends_on:
      - kafka

    ports:
      - "8081:8081"

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # kafka-connect:
  #   image: confluentinc/cp-kafka-connect:7.6.0
  #   depends_on: [ kafka ]
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
  #     CONNECT_REST_PORT: "8083"
  #     CONNECT_GROUP_ID: "parquet-connect-group"

  #     CONNECT_CONFIG_STORAGE_TOPIC: "_connect-configs"
  #     CONNECT_OFFSET_STORAGE_TOPIC: "_connect-offsets"
  #     CONNECT_STATUS_STORAGE_TOPIC: "_connect-status"
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"

  #     CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  #     CONNECT_VALUE_CONVERTER: "io.confluent.connect.protobuf.ProtobufConverter"
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  #     CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/plugins"

  #   volumes:
  #     - ./connect-plugins:/etc/kafka-connect/plugins
  #     - parquet-data:/data/parquet


  nifi:
    build:
      context: ./Nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
    volumes:
      - ./data:/opt/nifi/nifi-current/data_in

      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

    

    

volumes:
  parquet-data:
  elasticsearch-data: