spring.application.name=RainStreamAlert

server.port=8080
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.streams.application-id=rain-stream-alert
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.auto-offset-reset=earliest