apiVersion: v1
kind: ConfigMap
metadata:
  name: central-station-config
data:
  SPRING_APPLICATION_NAME: CentralStation
  BITCASK_PATH: ./bitcask_data
  BITCASK_MAX_FILE_SIZE: "10485760"
  BITCASK_COMPACTION_DELAY_MS: "600000"
  SERVER_PORT: "8085"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_GROUP_ID: central-station-group
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPECIFIC_PROTOBUF_VALUE_TYPE: com.diProject.broker.generated.StationMessage
