apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-kafka-config
data:
  metricbeat.yml: |
    metricbeat.modules:
      - module: kafka
        metricsets:
          - broker
          - consumergroup
          - partition
        period: 10s
        hosts:
          - "localhost:9092"

    processors:
      - add_host_metadata: {}

    setup.kibana:
      host: "http://kibana:5601"

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]