apiVersion: v1
kind: ConfigMap
metadata:
  name: station-stream-config
data:
  SPRING_APPLICATION_NAME: RainStreamAlert
  SERVER_PORT: "8087"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_STREAMS_APPLICATION_ID: rain-stream-alert
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
